import { ICard } from '../interfaces/card';

const data: ICard[] = [
    {
        id: 101,
        name: 't-shirt',
        title: 'Футболка с текстом',
        price: 180,
        size: ['S', 'M', 'L', 'XL'],
        color: ['красный', 'синий'],
        print: 'text',
        popular: 80,
        favorite: false,
        img: 'img 2.jpg',
        inStock: false,
    },
    {
        id: 102,
        name: 'sweatshirt',
        title: 'Свитшот с принтом на спине',
        price: 190,
        size: ['L', 'XL'],
        color: ['белый', 'синий'],
        print: 'print',
        popular: 30,
        favorite: false,
        img: 'img 1.jpg',
        inStock: true,
    },
    {
        id: 103,
        name: 'sweemcloth',
        title: 'Купальник однотонный',
        price: 200,
        size: ['S', 'M'],
        color: ['черный', 'синий'],
        print: 'no-print',
        popular: 20,
        favorite: false,
        img: 'img 3.jpg',
        inStock: true,
    },
    {
        id: 104,
        name: 'coat',
        title: 'Пальто барашек',
        price: 300,
        size: ['L'],
        color: ['синий', 'розовый'],
        print: 'no-print',
        popular: 50,
        favorite: false,
        img: 'img 4.jpg',
        inStock: true,
    },
    {
        id: 105,
        name: 'cardegan',
        title: 'Кардиган оверсайз',
        price: 320,
        size: ['L'],
        color: ['синий'],
        print: 'no-print',
        popular: 50,
        favorite: false,
        img: 'img 5.jpg',
        inStock: true,
    },
    {
        id: 106,
        name: 'coat',
        title: 'Пальто',
        price: 380,
        size: ['L'],
        color: ['серый', 'бежевый'],
        print: 'no-print',
        popular: 40,
        favorite: false,
        img: 'img 6.jpg',
        inStock: true,
    },
    {
        id: 107,
        name: 'cardegan',
        title: 'Кардиган укороченный',
        price: 250,
        size: ['L'],
        color: ['серый', 'бежевый'],
        print: 'no-print',
        popular: 50,
        favorite: false,
        img: 'img 7.jpeg',
        inStock: false,
    },
    {
        id: 108,
        name: 't-shirt',
        title: 'Футболка',
        price: 180,
        size: ['L'],
        color: ['серый', 'бежевый'],
        print: 'no-print',
        popular: 30,
        favorite: false,
        img: 'img 8.jpg',
        inStock: true,
    },
    {
        id: 109,
        name: 'cardegan',
        title: 'Кардиган с вязаным рисунком',
        price: 200,
        size: ['L'],
        color: ['серый', 'бежевый'],
        print: 'no-print',
        popular: 55,
        favorite: false,
        img: 'img 9.jpg',
        inStock: true,
    },
    {
        id: 110,
        name: 'cardegan',
        title: 'Кардиган с карманами',
        price: 220,
        size: ['L'],
        color: ['серый', 'бежевый'],
        print: 'no-print',
        popular: 60,
        favorite: false,
        img: 'img 10.jpg',
        inStock: true,
    },
    {
        id: 111,
        name: 'sweatshirt',
        title: 'Свитшот с укороченным рукавом',
        price: 350,
        size: ['L'],
        color: ['серый', 'бежевый'],
        print: 'no-print',
        popular: 70,
        favorite: false,
        img: 'img 11.jpg',
        inStock: false,
    },
    {
        id: 112,
        name: 'sweatshirt',
        title: 'Яркий свитшот',
        price: 370,
        size: ['L'],
        color: ['серый', 'бежевый'],
        print: 'print',
        popular: 90,
        favorite: false,
        img: 'img 12.jpg',
        inStock: true,
    },
];
export default data;
