import { ICard } from '../interfaces/card';

const data: ICard[] = [
    {
        id: 101,
        name: 't-shirt',
        title: 'Футболка с текстом',
        price: 180,
        size: ['S', 'M', 'L', 'XL'],
        color: ['красный', 'синий'],
        print: 'текст',
        popular: 80,
        favorite: false,
        img: '../../assets/img/img 2.jpg',
    },
    {
        id: 102,
        name: 'sweatshirt',
        title: 'Свитшот с принтом на спине',
        price: 190,
        size: ['L', 'XL'],
        color: ['белый', 'синий'],
        print: 'принт',
        popular: 30,
        favorite: false,
        img: '../../assets/img/img 1.jpg',
    },
    {
        id: 103,
        name: 'sweemcloth',
        title: 'Купальник однотонный',
        price: 200,
        size: ['S', 'M'],
        color: ['черный', 'синий'],
        print: 'однотонный',
        popular: 20,
        favorite: false,
        img: '../../assets/img/img 3.jpg',
    },
    {
        id: 104,
        name: 'coat',
        title: 'Пальто',
        price: 300,
        size: ['L'],
        color: ['синий'],
        print: 'однотонный',
        popular: 50,
        favorite: false,
        img: '../../assets/img/img 4.jpg',
    },
    {
        id: 105,
        name: 'cardegan',
        title: 'Кардеган',
        price: 320,
        size: ['L'],
        color: ['синий'],
        print: 'однотонный',
        popular: 50,
        favorite: false,
        img: '../../assets/img/img 5.jpg',
    },
    {
        id: 106,
        name: 'coat',
        title: 'Пальто',
        price: 350,
        size: ['L'],
        color: ['синий'],
        print: 'однотонный',
        popular: 50,
        favorite: false,
        img: '../../assets/img/img 1.jpg',
    },
];
export default data;
